import type { Dictionary, Post, Release } from "./en";

const de: Dictionary = {
  meta: {
    home: {
      title: "Janak Shrestha · Engineering Manager",
      description:
        "Janak Shrestha ist Engineering Manager bei Unzer in München und bringt zehn Jahre SRE-Erfahrung mit zuverlässigen, PCI-DSS-konformen Kubernetes-Plattformen auf AWS für Fintech mit.",
    },
    about: { title: "Über mich", description: "Über Janak Shrestha: Werdegang, Arbeitsprinzipien und Ausbildung eines Engineering Managers und ehemaligen Staff SRE aus München." },
    experience: { title: "Erfahrung", description: "Karriere-Changelog von Janak Shrestha: Unzer, Wirecard, Qualcomm, Huawei European Research Center und Websurfer Nepal." },
    stack: { title: "Stack", description: "Tools, Plattformen und Zertifizierungen: AWS, Kubernetes, Terraform, Argo CD, Datadog, CKA, CKAD, RHCE und mehr." },
    blog: { title: "Blog", description: "Notizen aus der Praxis zu SRE, Kubernetes, Terraform und On-Call von Janak Shrestha. Die ersten Beiträge erscheinen bald." },
    contact: { title: "Kontakt", description: "Kontakt zu Janak Shrestha zu Engineering Leadership, SRE, Platform Engineering und Kubernetes." },
    notFound: { title: "Seite nicht gefunden", description: "Diese Seite existiert nicht." },
  },

  nav: { "": "Start", about: "Über mich", experience: "Erfahrung", stack: "Stack", blog: "Blog", contact: "Kontakt" },

  ui: {
    skip: "Zum Inhalt springen",
    brandAria: "Janak Shrestha, Startseite",
    brandRole: "Engineering Manager · Unzer",
    navAria: "Hauptnavigation",
    mobileNav: "Mobile Navigation",
    themeToggle: "Farbschema wechseln",
    openMenu: "Menü öffnen",
    switchAria: "Read this page in English",
    city: "München, Deutschland",
    ctaHeading: <>Damit alles <em>läuft.</em></>,
    ctaButton: "Ticket eröffnen",
    status: "Status",
    operational: "Betriebsbereit: Engineering Manager bei Unzer, München.",
    uptime: "Karriere-Uptime:",
    pages: "Seiten",
    elsewhere: "Profile",
    resources: "Ressourcen",
    cvDownload: "Lebenslauf (PDF, Englisch)",
    email: "E-Mail",
    rights: "Alle Rechte vorbehalten",
    coords: "München, Deutschland · 48,137° N, 11,575° O",
    copy: "Kopieren",
    copied: "Kopiert",
    sending: "Nachricht wird gesendet…",
    sent: "✓ Zugestellt. Ich melde mich bald bei Ihnen.",
    sentToast: "Nachricht zugestellt",
    failed: "Senden fehlgeschlagen. Bitte schreiben Sie mir direkt per E-Mail.",
    collapse: "Änderungen einklappen",
    showMore: (n: number) => (n === 1 ? "1 weitere Änderung anzeigen" : `${n} weitere Änderungen anzeigen`),
    clockUnits: ["J", "T", "h", "m", "s"],
  },

  home: {
    eyebrow: "Engineering Manager — München",
    edition: "Portfolio · Ausgabe 2026",
    titleLead: "Ich mache Fintech-",
    titleIndent: "Plattformen",
    swap: ["zuverlässig.", "beobachtbar.", "sicher.", "skalierbar."],
    intro: (
      <>
        Ich bin <strong>Janak Shrestha</strong>, Engineering Manager bei <strong>Unzer</strong>. Bevor ich das Team übernommen habe, war ich
        jahrelang selbst SRE: Ich habe AWS- und Kubernetes-Plattformen für den Zahlungsverkehr entworfen und betrieben, die Infrastruktur in
        Terraform beschrieben und dafür gesorgt, dass der Pager um 3&nbsp;Uhr nachts still bleibt.
      </>
    ),
    ctaPrimary: "Zum Changelog",
    ctaCv: "Lebenslauf (EN)",
    card: {
      aria: "Werdegang auf einen Blick",
      label: "Zeit in der IT · live",
      units: ["Jahre", "Tage", "Std.", "Min.", "Sek."],
      note: "Gezählt seit meinem ersten Job als Systemadministrator in Kathmandu im März 2013.",
      rows: [
        ["Aktuell", "Engineering Manager bei Unzer"],
        ["Standort", "München, Deutschland"],
        ["Fokus", "Plattform-Teams · Kubernetes · AWS"],
      ],
    },
    band: {
      aria: "Foto: Eibsee unterhalb der Zugspitze",
      alt: "Janak sitzt auf einem Felsen am zugefrorenen Eibsee und zeigt auf das Zugspitzmassiv",
      caption: <>Ruhige Systeme, <em>klare</em> Köpfe, hohe Gipfel.</>,
      place: "Eibsee · Bayern · 47,45° N",
    },
    numbers: {
      num: "(01) — In Zahlen",
      title: <>Über zehn Jahre <em>Produktion</em>.</>,
      lead: "Von RHEL-Servern im Rechenzentrum in Kathmandu bis zu PCI-DSS-konformem Kubernetes in Deutschland: Die Aufgabe war immer dieselbe. Kritische Systeme am Laufen halten und sie jedes Jahr einfacher betreibbar machen.",
      stats: [
        { n: 10, plus: true, text: "Amazon-EKS-Cluster aufgebaut, darunter PCI-DSS-konforme" },
        { n: 500, plus: true, text: "Linux-VMs im eigenen Rechenzentrum bereitgestellt und betreut" },
        { n: 100, plus: true, text: "Anwendungen on-prem und in AWS betrieben" },
        { n: 9, plus: false, text: "Branchenzertifizierungen, darunter CKA, CKAD und RHCE" },
      ],
    },
    services: {
      num: "(02) — Leistungen",
      title: <>Was ich für Teams <em>betreibe</em>.</>,
      lead: "Fahren Sie über eine Zeile, um sie aufzuklappen. Alles davon habe ich selbst aufgebaut und in Produktion im On-Call verantwortet.",
      rows: [
        { title: "Container-Orchestrierung", text: "Produktionsreifes Amazon EKS von Sandbox bis Produktion, mit wiederverwendbaren Terraform-Modulen, Helm-Charts und GitOps über Argo CD. Ich habe On-Premises-Monolithen in Microservices überführt und PCI-DSS-konforme Cluster für den Zahlungsverkehr aufgebaut.", tags: ["EKS", "Helm", "Argo CD", "PCI-DSS"] },
        { title: "Infrastructure as Code", text: "AWS-Infrastruktur, vollständig mit Terraform bereitgestellt, dazu Ansible und Puppet für die Konfiguration. Umgebungen sind reproduzierbar, geprüft und auditierbar, und niemand klickt sich durch die Konsole.", tags: ["Terraform", "AWS", "Ansible", "Puppet"] },
        { title: "Observability & On-Call", text: "Datadog APM und Agents per Terraform ausgerollt, zentrales Logging mit OpenSearch und Fluentd sowie Opsgenie-Rotationen mit klaren Runbooks. Incidents enden mit einer Ursachenanalyse, nicht mit Vermutungen.", tags: ["Datadog", "OpenSearch", "Fluentd", "Opsgenie"] },
        { title: "CI/CD-Konsolidierung", text: "Ich führe verstreute CI/CD-Tools, Registries, SCM und Code-Review in einer sicheren Toolchain zusammen und automatisiere Tests, Releases und Deployments, damit weniger Schritte einen Menschen brauchen.", tags: ["GitLab CI", "GitHub Actions", "Jenkins", "Nexus · ECR"] },
      ],
    },
    now: {
      eyebrow: "Aktuell",
      title: <>Jetzt <em>in Führung</em> bei Unzer.</>,
      meta: "Engineering Manager · München · seit 04/2026",
      heading: "Vom Aufbau der Plattform zur Führung des Teams dahinter.",
      text: "Nach fünfeinhalb Jahren bei Unzer als Senior und anschließend Staff SRE bin ich im April 2026 ins Engineering Management gewechselt. Als SRE habe ich dort umgesetzt:",
      list: [
        "Wiederverwendbare Terraform-Module für EKS über Sandbox, Dev, Int, Test und Prod",
        "Eine konsolidierte Toolchain aus CI/CD, Registry und SCM für mehr Sicherheit und Transparenz",
        "PCI-DSS-konforme Infrastruktur, mit zertifiziertem technischem Scoping seit 2025",
      ],
    },
    index: {
      num: "(03) — Übersicht",
      title: <>Weiter <em>entdecken</em>.</>,
      aria: "Bereiche der Website",
      cards: {
        about: ["Die Person", "Werdegang, Prinzipien, Ausbildung"],
        experience: ["Der Changelog", "Sieben Releases seit 2013"],
        stack: ["Die Tools", "Tools & Zertifizierungen"],
        blog: ["Die Notizen", "Praxisnotizen, bald online"],
        contact: ["Der Pager", "Eröffnen Sie ein Ticket bei mir"],
        cv: ["Der Lebenslauf", "Vollständiger CV (Englisch)"],
      },
    },
  },

  about: {
    eyebrow: "02 — Über mich",
    meta: "München, Deutschland · aus Nepal",
    title: <>Ingenieur für <em>ruhige</em> Pager.</>,
    lead: "Ich habe in Telekommunikation, Banking und Zahlungsverkehr gearbeitet. In jeder Rolle habe ich kritische Systeme am Laufen gehalten und ihren Betrieb einfacher gemacht. Heute führe ich die Engineers, die genau das tun.",
    photoAlt: "Janak am zugefrorenen Eibsee vor der Zugspitze",
    photoCaption: "Eibsee, Bayern · Hover für Farbe",
    facts: [
      ["Rolle", "Engineering Manager"],
      ["Unternehmen", "Unzer, München"],
      ["Branche", "Fintech · Zahlungsverkehr · Kartenausgabe"],
      ["Sprachen", "Englisch, Deutsch, Nepali"],
      ["Im Betrieb seit", "2013"],
    ],
    prose: [
      "Ich bin ein eigenständiger, lösungsorientierter Engineer mit einer Leidenschaft für Cloud Computing und Kubernetes. Ich übernehme gern Verantwortung für komplexe Aufgaben und liefere hochwertige Umsetzungen. Heute helfe ich einem Team, genau das zu tun.",
      "Mein Weg begann 2013 als Systemadministrator bei Websurfer Nepal. Dort betrieb ich RHEL- und CentOS-Server für DNS, Mail, LDAP und Datenbanken und richtete Netzwerk-Monitoring mit Nagios, Cacti und OpenNMS ein. Danach kam ich für einen Master in Information & Communication Engineering nach Deutschland. Für meine Abschlussarbeit am Huawei European Research Center in München erweiterte ich den Open-Source-SDN-Emulator Mininet, sodass er Docker-Container als Netzwerkfunktionen ausführen kann.",
      "Bei Qualcomm testete ich anschließend LTE-Modems im Feld, quer durch Europa und auf Infrastruktur von Ericsson, Huawei und Nokia. Dann wechselte ich zu Wirecard in die Fintech-Branche. Dort betreute ich über 500 Linux-VMs und mehr als 200 EC2-Instanzen hinter einer Plattform für Kartenausgabe und wechselte später ins SRE-Team, um wiederkehrende Betriebsarbeit wegzuautomatisieren.",
      "2020 kam ich als Senior SRE zu Unzer und wurde später Staff SRE. Ich baute wiederverwendbare Terraform-Module für Amazon EKS, überführte Monolithen in Microservices, rollte Datadog APM und Logging mit OpenSearch aus und betreute PCI-DSS-konforme Infrastruktur. Im April 2026 wurde ich Engineering Manager.",
      "Ich arbeite eng mit Entwicklern und Cloud-Engineers zusammen. Was ich lerne, halte ich in SOPs und Runbooks fest, und ein Problem gilt für mich erst dann als gelöst, wenn die eigentliche Ursache behoben ist.",
    ],
    cvButton: "Lebenslauf (EN)",
    principles: {
      num: "(01) — Arbeitsprinzipien",
      title: <>Wie ich <em>arbeite</em>.</>,
      lead: "Vier Gewohnheiten aus mehr als zehn Jahren Produktionsbetrieb.",
      items: [
        ["Alles als Code", "Infrastruktur, Pipelines und Alerts liegen in Git, werden wie Anwendungscode geprüft und lassen sich jederzeit von Grund auf neu aufbauen."],
        ["Toil automatisieren", "Kommt eine Aufgabe zweimal vor, schreibe ich ein Skript dafür. Beim dritten Mal bekommt sie eine Pipeline."],
        ["Ursache statt Schuld", "Incidents sind zum Lernen da. Jedes Post-Mortem endet mit einer Verbesserung am System, nicht mit einem Vorwurf an eine Person."],
        ["Sicher von Anfang an", "Compliance (PCI-DSS) baue ich von Beginn an in die Plattform ein. Audits bestätigen dann nur noch, was bereits vorhanden ist."],
      ],
    },
    education: {
      num: "(02) — Ausbildung",
      title: <>Wo alles <em>begann</em>.</>,
      items: [
        { meta: "2014 — 2016 · Friedberg, Deutschland", title: "M.Sc. Information & Communication Engineering", text: "Technische Hochschule Mittelhessen (THM). Vortrag zu einem wissenschaftlichen Paper über OpenStack Cloud Computing (2015). Abschlussarbeit am Huawei European Research Center zu SDN und Container-Networking.", mark: "M.Sc" },
        { meta: "Nepal", title: "B.Eng. Elektronik- & Kommunikationstechnik", text: "Grundlagen in Netzwerken, Signalen und Systemen, die mich zu meiner ersten Stelle als Systemadministrator in Kathmandu geführt haben.", mark: "B.Eng" },
      ],
    },
  },

  experience: {
    eyebrow: "03 — Erfahrung",
    meta: "CHANGELOG.md · 7 Releases · 2013 → heute",
    title: <>Der Karriere-<em>Changelog</em>.</>,
    lead: "Jede Rolle ist ein Release, das neueste steht oben. Jede Änderung ist nach Art gekennzeichnet.",
    legend: { feat: "etwas Neues gebaut", ops: "Betrieb & Zuverlässigkeit", sec: "Sicherheit & Compliance", perf: "Effizienz & Automatisierung" },
    releases: [
      {
        ver: "v7.0 · aktuell", latest: true, date: "04/2026 — heute", title: "Engineering Manager", company: "Unzer", location: "München",
        tag: "Staff SRE → Engineering Manager",
        summary: "Nach fünfeinhalb Jahren als SRE bei Unzer bin ich ins Engineering Management gewechselt. Heute führe ich die Engineers, die die Plattform aufbauen und betreiben.",
        changes: [{ kind: "feat", text: "Vom Staff SRE zum Engineering Manager befördert" }],
      },
      {
        ver: "v6.0", date: "09/2020 — 03/2026", title: "Staff Site Reliability Engineer", company: "Unzer", location: "München / Heidelberg",
        tag: "Senior SRE → Staff SRE",
        summary: "Ich habe die Zuverlässigkeit der Plattform eines europäischen Payment-Unternehmens verantwortet. Ich kam als Senior SRE und wurde zum Staff SRE befördert. In dieser Rolle gab ich die Richtung für Cloud-Infrastruktur, Tooling und Compliance vor.",
        visible: 5,
        changes: [
          { kind: "feat", text: "Wiederverwendbares Terraform-Modul für Amazon EKS, ausgerollt in Sandbox, Dev, Int, Test und Produktion" },
          { kind: "feat", text: "On-Premises-Monolithen in Microservices auf EKS überführt" },
          { kind: "sec", text: "Infrastruktur nach PCI-DSS-Standard aufgebaut" },
          { kind: "perf", text: "CI/CD-Tools, Registry, SCM und Code-Review konsolidiert, für mehr Sicherheit und Transparenz bei weniger Betriebsaufwand" },
          { kind: "ops", text: "Datadog APM per Terraform ausgerollt, inklusive Agent-Integration" },
          { kind: "feat", text: "Zentrales Logging mit OpenSearch und Fluentd-Integration aufgebaut" },
          { kind: "feat", text: "Helm-Charts für Microservices geschrieben und über Argo CD released" },
          { kind: "feat", text: "AWS-Cloud-Infrastruktur vollständig mit Terraform bereitgestellt" },
          { kind: "feat", text: "Nexus und ECR als Artefakt-Repositories eingerichtet" },
          { kind: "ops", text: "Produktiver On-Call mit Opsgenie: Incident-Handling, Problemanalyse und RCA" },
          { kind: "ops", text: "Fehlersuche bei Service-Ausfällen, Konfigurationsproblemen und CI/CD-Pipelines" },
          { kind: "perf", text: "Build-Prozesse verbessert, um die Auslieferung zu automatisieren und zu beschleunigen" },
          { kind: "sec", text: "Laufendes System-Patching und Standard Operating Procedures (SOPs)" },
        ],
        stack: ["AWS", "EKS", "Terraform", "Helm", "Argo CD", "Datadog", "OpenSearch", "Opsgenie"],
      },
      {
        ver: "v5.0", date: "01/2020 — 08/2020", title: "Site Reliability Engineer", company: "Wirecard Issuing Technologies", location: "Aschheim",
        summary: "Wechsel vom Anwendungsbetrieb ins SRE, mit Fokus auf Architektur, Kosten und dem Abbau von Toil.",
        changes: [
          { kind: "perf", text: "Architekturänderungen empfohlen, die Effizienz, Zuverlässigkeit und Performance verbessern und gleichzeitig Kosten senken" },
          { kind: "perf", text: "Wiederkehrende Betriebsaufgaben automatisiert" },
          { kind: "feat", text: "Mehrere Infrastrukturprojekte geplant, aufgebaut und ausgeliefert" },
        ],
      },
      {
        ver: "v4.0", date: "09/2018 — 12/2019", title: "Application Engineer", company: "Wirecard Issuing Technologies", location: "Aschheim",
        summary: "DevOps und L3-Support für ein digitales Banking- und Kartenausgabesystem, im eigenen Rechenzentrum und in AWS.",
        visible: 5,
        changes: [
          { kind: "ops", text: "Anwendungen auf über 500 Linux-VMs on-prem und mehr als 200 EC2-Instanzen in AWS bereitgestellt und betreut" },
          { kind: "ops", text: "Über 60 Anwendungen im Rechenzentrum und mehr als 40 in AWS betrieben, in QA, Test und Produktion" },
          { kind: "ops", text: "Wöchentliche On-Call-Rotation für Produktionssupport und L3-Incidents" },
          { kind: "sec", text: "Zertifikatsverwaltung und Security-Patching" },
          { kind: "ops", text: "Proaktives Monitoring mit Checkmk und Datadog" },
          { kind: "feat", text: "Spring-Boot-, Tomcat- und WebLogic-Server konfiguriert" },
          { kind: "feat", text: "Hochverfügbare Apache-Load-Balancer und Rewrite-Regeln" },
          { kind: "perf", text: "Shell-Skripte für Control-M-Jobs" },
          { kind: "feat", text: "Tägliche Banking-Report-Jobs in SQL sowie DDL-/DML-Operationen mit PL/SQL" },
          { kind: "ops", text: "Anwendungs-Releases und Bugfixing mit den Entwicklern, Backup und Archivierung von Logs" },
          { kind: "ops", text: "SOP-Dokumentation in Confluence" },
        ],
        stack: ["AWS EC2", "Linux", "Apache", "Oracle", "Checkmk", "Datadog"],
      },
      {
        ver: "v3.0", date: "02/2017 — 06/2018", title: "Systemadministrator / Modem-Testingenieur", company: "Qualcomm CDMA Technologies", location: "Sulzbach (Taunus)",
        summary: "Feldtests von Modems in ganz Europa, über alle Mobilfunkgenerationen von GSM bis LTE-Advanced.",
        visible: 3,
        changes: [
          { kind: "ops", text: "Feldtests auf Infrastruktur von Ericsson, Huawei und Nokia: GSM, GPRS, EDGE, UMTS, HSPA+, LTE und LTE-A" },
          { kind: "feat", text: "KPI-Management für Modems mit Log-Analyse und Reporting" },
          { kind: "ops", text: "IMS-Funktionstests, Regressionstests und Stabilitätstests im Feld" },
          { kind: "perf", text: "Bash-Skripte zur Automatisierung von Testabläufen" },
          { kind: "ops", text: "Arbeit mit den Qualcomm-Tools QXDM, APEX und QPST sowie Gerätevorbereitung (Flashen, Upgrades, Kalibrierung)" },
        ],
      },
      {
        ver: "v2.0", date: "01/2016 — 01/2017", title: "Masterarbeit & Praktikum", company: "Huawei European Research Center", location: "München",
        summary: "Forschung zu Software-Defined Networking und Container-Networking, mit Beiträgen zu einem Open-Source-Emulator.",
        changes: [
          { kind: "feat", text: "Den Open-Source-SDN-Emulator Mininet in Python erweitert" },
          { kind: "feat", text: "Docker-Container als Data-Plane-Knoten in Mininet-Netztopologien bereitgestellt" },
          { kind: "feat", text: "Container als Open vSwitch emuliert, für die Platzierung von Netzwerkfunktionen und SDN-Controller-Knoten" },
          { kind: "feat", text: "Container auf verschiedenen physischen Servern über SSH-Layer-2-Tunnel verbunden" },
        ],
        stack: ["Python", "Docker", "Mininet", "Open vSwitch", "SDN"],
      },
      {
        ver: "v1.0", date: "03/2013 — 08/2014", title: "Systemadministrator", company: "Websurfer Nepal Communication System", location: "Kathmandu, Nepal",
        summary: "Meine erste Rolle im Produktionsbetrieb: die Linux-Serverlandschaft eines Internetanbieters von A bis Z.",
        changes: [
          { kind: "ops", text: "RHEL- und CentOS-Server installiert, optimiert, gepatcht und Fehler behoben, für DNS, Apache, Mail, MySQL, LDAP und Fileserver" },
          { kind: "feat", text: "Netzwerk-Monitoring mit MRTG, Cacti, Nagios und OpenNMS" },
          { kind: "feat", text: "KVM-Virtualisierung sowie Backup- und Logging-Lösungen" },
          { kind: "sec", text: "Firewall-Konfiguration und Shell-Skripting" },
        ],
        stack: ["RHEL", "CentOS", "KVM", "Nagios", "Bash"],
      },
    ] as Release[],
  },

  stack: {
    eyebrow: "04 — Stack",
    meta: "9 Bereiche · 40+ Tools · 9 Zertifizierungen",
    title: <>Der <em>Werkzeugkasten</em>, nach Bereichen.</>,
    lead: (core) => <>Diese Tools habe ich in Produktion, in der Forschung oder in beidem eingesetzt. Tools mit einem Punkt {core} nutze ich täglich.</>,
    coreLabel: "Kern",
    filterAria: "Bereiche filtern",
    filters: { all: "Alle", platform: "Platform", delivery: "Auslieferung", observe: "Observability", systems: "Systeme" },
    categories: {
      cloud: ["Cloud", "AWS-Infrastruktur für regulierte Payment-Workloads."],
      containers: ["Container", "Orchestrierung und Paketierung für Microservices."],
      iac: ["Infrastructure as Code", "Reproduzierbare, geprüfte Umgebungen."],
      cicd: ["CI/CD & GitOps", "Vom Commit bis zum Cluster, mit möglichst wenig Handarbeit."],
      scm: ["SCM & Artefakte", "Quellcode und Binärdateien, konsolidiert und abgesichert."],
      monitoring: ["Monitoring & On-Call", "Metriken, APM und Alerting, die die richtige Person erreichen."],
      logging: ["Logging", "Zentrale, durchsuchbare Logs für jeden Service."],
      os: ["Betriebssysteme & Web", "Die Schicht, auf der alles andere läuft."],
      scripting: ["Skripte & Daten", "Glue-Code, Automatisierung und Datenbanken."],
    },
    certs: {
      num: "(02) — Zertifizierungen",
      title: <>Zertifiziert, <em>nachweislich</em>.</>,
      lead: "Kubernetes, Linux, Netzwerke, Datenbanken und Compliance. Fahren Sie über ein Siegel, damit es sich dreht.",
      names: {
        "PCI DSS": "Technisches Scoping für Admins · 2025",
        CKA: "Certified Kubernetes Administrator",
        CKAD: "Certified Kubernetes Application Developer",
        RHCE: "Red Hat Certified Engineer",
        RHCSA: "Red Hat Certified System Administrator",
        CCNP: "Cisco Certified Network Professional",
        CCNAS: "CCNA Security",
        CCNA: "Cisco Certified Network Associate",
        "Oracle 11g": "Oracle Database 11g Administrator",
      },
    },
  },

  blog: {
    eyebrow: "05 — Blog",
    status: "Status: in Arbeit · erster Beitrag bald",
    title: <>Notizen aus der Praxis, <em>in Arbeit</em>.</>,
    lead: "Der Blog startet bald. Ich schreibe auf, was ich in mehr als zehn Jahren Produktionsbetrieb gelernt habe: Kubernetes, Terraform, Compliance, die menschliche Seite des On-Call und jetzt den Schritt ins Engineering Management. Der erste Beitrag ist im Review.",
    pipeline: {
      aria: "Veröffentlichungs-Pipeline: Gliederung und Entwurf bestanden, Review läuft, Veröffentlichung in der Warteschlange",
      name: "pipeline · blog/erster-beitrag",
      run: "Lauf #001",
      stages: [
        ["Gliederung", "bestanden", "done"],
        ["Entwurf", "bestanden", "done"],
        ["Review", "läuft…", "run"],
        ["Veröffentlichung", "wartet", "wait"],
      ],
    },
    queue: {
      num: "(01) — In der Warteschlange",
      title: <>Was <em>kommt</em>.</>,
      lead: "An diesen Themen arbeite ich gerade. Die Titel können sich bis zur Veröffentlichung noch ändern.",
    },
    posts: [
      { cover: "eks", tag: "Kubernetes · Terraform", state: { label: "Im Review", tone: "review" }, title: "Ein Terraform-Modul, fünf EKS-Umgebungen", summary: "Wie ein wiederverwendbares Modul Sandbox, Dev, Int, Test und Prod konsistent hält und was ich heute anders machen würde." },
      { cover: "pci", tag: "Compliance", state: { label: "Im Entwurf", tone: "draft" }, title: "PCI-DSS auf Kubernetes, ganz ohne Panik", summary: "Scoping, Netzwerksegmentierung und Nachweise für Workloads mit Kartendaten auf EKS." },
      { cover: "monolith", tag: "Architektur", state: { label: "Im Entwurf", tone: "draft" }, title: "Vom Monolithen zu Microservices, ohne Big Bang", summary: "Erfahrungen aus der schrittweisen Migration von On-Premises-Payment-Services nach EKS." },
      { cover: "oncall", tag: "Zuverlässigkeit", state: { label: "Gegliedert" }, title: "On-Call, ohne auszubrennen", summary: "Saubere Alerts, Runbooks und Rotationen, die Pager ruhig und Menschen ausgeruht halten." },
      { cover: "logging", tag: "Observability", state: { label: "Gegliedert" }, title: "Zentrales Logging mit OpenSearch und Fluentd", summary: "Eine Log-Pipeline aufbauen, die Teams wirklich durchsuchen, und dabei die Kosten im Griff behalten." },
      { cover: "sdn", tag: "Netzwerke", state: { label: "Geplant" }, title: "Von Mininet zum Kubernetes-Networking", summary: "Was mir meine Abschlussarbeit über SDN und Container für das Networking in heutigen Clustern beigebracht hat." },
    ] as Post[],
    notify: {
      eyebrow: "Benachrichtigung",
      title: <>Als Erste:r <em>lesen</em>.</>,
      text: "Ich schicke eine einzige E-Mail, sobald der erste Beitrag online ist. Kein Newsletter, kein Spam.",
      label: "Ihre E-Mail-Adresse",
      button: "Benachrichtigen",
      success: "✓ Sie stehen auf der Liste. Danke!",
    },
  },

  contact: {
    eyebrow: "06 — Kontakt",
    title: <>Ein <em>Ticket</em> eröffnen.</>,
    lead: "Sie haben eine Plattform, die stabiler werden soll, ein Team, das wachsen soll, oder eine offene Stelle? Schreiben Sie mir. Ich lese jede Nachricht.",
    direct: "Direkter Draht",
    facts: [
      ["Standort", "München, Bayern, Deutschland"],
      ["Offen für", "Engineering Leadership, SRE- & Plattform-Themen, Vorträge"],
      ["Sprachen", "English · Deutsch · नेपाली"],
    ],
    socialsAria: "Social-Media-Profile",
    topicsLegend: "Worum geht es?",
    topics: ["Stelle / Recruiting", "Beratung", "Vortrag", "Einfach Hallo sagen"],
    name: "Ihr Name",
    email: "E-Mail-Adresse",
    subject: "Betreff",
    message: "Nachricht",
    send: "Nachricht senden",
  },

  notFound: {
    eyebrow: "Incident · Sev-4 · Seite nicht gefunden",
    text: "Diese Route hat keinen gesunden Upstream geliefert. Der On-Call-Engineer ist alarmiert, aber am schnellsten geht es zurück zur Startseite.",
    home: "Zur Startseite",
    report: "Melden",
  },
};

export default de;
